# Generated by Django 5.1.3 on 2024-11-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="body",
            field=models.TextField(default=""),
        ),
    ]
