# Generated by Django 5.1.3 on 2024-11-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boid',
            fields=[
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('userName', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, default='#A63E26', max_length=7)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('velocity_x', models.IntegerField()),
                ('velocity_y', models.IntegerField()),
                ('acceleration_x', models.IntegerField()),
                ('acceleration_y', models.IntegerField()),
            ],
            options={
                'ordering': ['dateJoined'],
            },
        ),
    ]
